# Generated by Django 5.0.7 on 2024-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='application_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
